### ISSUE TITLE
Certain color aliases are missing in the UdonConsole

### ISSUE THREAD

**Issue by techanon** [Varneon/VUdon-Logger#23]
So far I've noticed at least `silver` and `magenta` aren't being color converted properly.

![image](https://github.com/Varneon/VUdon-Logger/assets/1837484/2aa728ff-5bd0-4b9d-aab8-d2477a9a2a15)

Reference: https://docs.unity3d.com/2018.3/Documentation/Manual/StyledText.html

**Comment by Varneon** [comment]
UdonConsole was recently (#16) migrated to use [TextMeshProUGUI](https://docs.unity3d.com/Packages/com.unity.textmeshpro@2.1/api/TMPro.TextMeshProUGUI.html) instead of native [Unity UI Text](https://docs.unity3d.com/Packages/com.unity.ugui@1.0/manual/script-Text.html) components, and not all rich color tags are supported anymore.

Wiki page: https://github.com/Varneon/VUdon-Logger/wiki/UdonConsole:-Supported-Rich-Text-Color-Tags
