### ISSUE TITLE
Invalid Dependencies

### ISSUE THREAD

**Issue by ElMoha943** [Varneon/VUdon-Logger#41]
Hi, im trying to install this on my project but im getting missing dependencies errors. I installed both v-inspector and neon-inspector. Im using unity 2022.3.6f1 and VRC SDK 3.5.1
![image](https://github.com/Varneon/VUdon-Logger/assets/25410859/99ca6e3e-39f0-4b1f-a7b1-622022ba000a)

**Comment by Varneon** [comment]
Hi,

Starting from version `0.4.0-alpha.1` the previous dependencies, `V-Inspector` and `Neon-Inspector` are obsolete, and were replaced by [VUdon - Editors](https://github.com/Varneon/VUdon-Editors).

The reason for this change was the fact that V-Inspector was deemed too unstable due to being developed using experimental Unity features.

Unfortunately the new dependency of the alpha version of the logger is only visible when viewing the [`0.4.0`](https://github.com/Varneon/VUdon-Logger/tree/0.4.0) branch and GitHub allows you to download pre-releases without seeing the up-to-date dependencies at this time. I will add a notice about this to the existing pre-releases.

Importing the new `VUdon - Editors` package into the project should fix the issue, it will not conflict with the previous dependencies. If no other package is using `V-Inspector` or `Neon-Inspector`, they can be safely removed afterwards.

-Varneon

**Comment by ElMoha943** [comment]
Hi, thanx you for the quick response. One last question: im also using noclip and other of your packages that depend on v-inspector, do they work with vudon-editors?

**Comment by Varneon** [comment]
Yes, if I recall correctly, all VUdon ecosystem packages should already be updated to use VUdon - Editors instead.

Noclip's latest pre-release actually does have a notice about updated dependencies: https://github.com/Varneon/VUdon-Noclip/releases/tag/0.3.0-alpha.2
